# Generated by Django 5.1.4 on 2025-01-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_prince_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desciption',
            new_name='description',
        ),
    ]
